### ISSUE TITLE
Thanks for the demo!

### ISSUE THREAD

**Issue by back-2-95** [ocrampete16/symfony-ux-turbo-demo#1]
Hi! I found your demo and made alternative version of it: https://github.com/druidfi/symfony-ux-turbo-demo

Changes:

- Symfony packages updated to latest stable version
- Symfony Docker instead of local server
- Stonehenge https://github.com/druidfi/stonehenge (Traefik driven dev tool)
- Tailwind CSS basic setup
- PostgreSQL database

Thank you again!

**Comment by ocrampete16** [comment]
That looks really nice. Great job! Love the color gradient background :)

And thanks as well! Really appreciate you reaching out 👍
